---
name: opensearch

services:
  opensearch-node:
    container_name: opensearch-node
    image: opensearchproject/opensearch:latest
    network_mode: host
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    environment:
      - "TZ=${DEVICE_TIMEZONE}"
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node # Name the node that will run in this container
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    volumes:
      - volume_opensearch_node:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container

volumes:
  volume_opensearch_node:
    external: true
